language: node_js
node_js:
  - "0.8"
before_install:
  # Run tests completely in the cloud using Travis CI and Sauce Labs
  # https://saucelabs.com/opensource/travis
  # http://saucelabs.com/downloads/Sauce-Connect-latest.zip
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash &> sauce_connect_setup.log
  - npm install -g grunt-cli testem vows
before_script:
  - npm test
script:
  # java -jar node_modules/karma-sauce-launcher/node_modules/sauce-connect-launcher/lib/Sauce-Connect.jar $SAUCE_USERNAME $SAUCE_ACCESS_KEY --tunnel-identifier $TRAVIS_JOB_NUMBER
  # node spec/lib/saucelauncher-webdriver.js --connect --localhostSL='localhost:7357' --browserNameSL='chrome' --versionSL='' --platformSL='Linux'
  - vows spec/vows/js/* --spec
  - vows spec/vows/js/* --spec --browserNameSL='ipad' --versionSL='6' --platformSL='OS X 10.8'
  - testem ci -P 3 -f testem.yml --port 8080

# Run tests using Travis CI and Sauce Labs
# https://saucelabs.com/opensource/travis
#
# Secure environment variables
# http://about.travis-ci.org/docs/user/build-configuration/#Secure-environment-variables
env:
  global:
    - secure: "cOSqllxPSc4DmtVO8xuRQecl4Sl16Iwhckv4ue1u/WQ+GtTv0+Io70jhOpuG\nPmb/dbwmWJa4KqR/+esVogn6mc9nidqkGyp9mjRsAOFlvKnNf0nb6quAA8NW\nt243y08VmFR/VtCJUEB6VVdnFlXBkH+ZyRpanHQ+yyJpRBFPY8Q="
    - secure: "RKUzw2WNe+qknVKIs/SCcQCPTTqRdBkNznnR9f7QODPpwV9Vqmm8tEK01eXp\nUrir1BChJlBOYgYez+mnGgDfQagd8tlI16aqWnCQaHcKvwMx5EUSur2GkMZE\nHvgGUtRiQF66ZxqxrnqDyaRzKTInAvqxZQAIz6csSwd8IzKTfao="
