language: node_js
node_js:
  - "0.11"
before_script:
  # Run tests completely in the cloud using Travis CI and Sauce Labs
  # https://saucelabs.com/opensource/travis
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
  - npm install -g grunt-cli
script:
  - grunt
  - vows spec/vows/js/*

# Run tests using Travis CI and Sauce Labs
# https://saucelabs.com/opensource/travis
#
# Secure environment variables
# http://about.travis-ci.org/docs/user/build-configuration/#Secure-environment-variables
env:
  global:
    - secure: "XDZMq2j2QIdsf2TIiOJV/BzLUDNOMv+fepsfhTB72UbjOpw18oUCQg9I1kbj\n6f5HFXxjmAd+Eqi2/jGltVsOKFXzq8mYg0WpajMNKG+IKzCo6p+BjX4DiYKK\niEvprgXFvffK6uyoUZs+ysn8IvkqEqAtbycM0JpE5VJuva+lr3A="
    - secure: "j8scT7feztRHZu/Eqz4eY9WhXvZD4HyqJ0KwOzedDFOUuVkWlEodm1mf86Fu\n3NGp4bMoUAEnCKaxCAz6DfenCRzHN7HGMWnzblUxhL1Uqe5saD+fAQKc51FI\nATJy114yLxQdPJDK0MjhNekJlSC7e7pIEzlFle9Br/kAc+Ua/Ik="
